name: 'Send Slack Message'
description: 'Sends a message to a specified Slack channel'

inputs:
  slack_token:
    description: 'Slack Bot User OAuth Token'
    required: true
  payload:
    description: 'JSON payload to send to Slack'
    required: true
  method:
    description: 'Slack method to call'
    required: true
    default: 'chat.postMessage'
  dry_run:
    description: 'Only print output'
    required: false
    default: ""

runs:
  using: 'composite'

  steps:
  - name: Context
    id: context
    shell: bash
    env:
      payload: ${{ inputs.payload }}
      method: ${{ inputs.method }}
    run: |
      echo "Sending slack API call"
      echo "method: $method"
      echo "token: ***"
      echo "---- payload ----"
      echo "${payload}"

  - name: Send Message
    if: ${{ inputs.dry_run != '' }}
    uses: slackapi/slack-github-action@v2.0.0
    with:
      errors: true
      token: ${{ inputs.slack_token }}
      method: ${{ inputs.method }}
      payload: ${{ inputs.payload }}
