name: 'Send Slack Message'
description: 'Sends a message to a specified Slack channel'

inputs:
  slack_token:
    description: 'Slack Bot User OAuth Token'
    required: true
  payload:
    description: 'JSON payload to send to Slack'
    required: true
  method:
    description: 'Slack method to call'
    required: true
    default: 'chat.postMessage'
  dry_run:
    description: 'Only print output'
    required: false

runs:
  using: 'composite'

  steps:
  - name: Validate payload
    shell: bash
    env:
      payload: ${{ inputs.payload }}
    run: |
      if [ -z "${payload}" ]; then
        echo "payload is empty"
        exit 1
      fi

      # Validate that payload is valid YAML
      echo "${payload}" | yq e '.'

      # Validate that payload has "channel" field
      channel_value=$(echo "${payload}" | yq e '.channel' -)
      echo "channel_value=${channel_value}"
      if [ "${channel_value}" = "null" ] || [ -z "${channel_value}" ]; then
        echo "payload is missing channel field"
        exit 1
      fi

  - name: Context
    id: context
    shell: bash
    env:
      dry_run: ${{ inputs.dry_run }}
    run: |
      send_message=true

      if [ -n "${dry_run}" ] && [ "${dry_run}" != "false" ] && [ "${dry_run}" != "null" ]; then
        send_message=false
      fi

      echo "send_message=${send_message}" >> "${GITHUB_OUTPUT}"
      cat "${GITHUB_OUTPUT}"

  - name: Send Message (dry run)
    if: ${{ steps.context.outputs.send_message == 'false' }}
    shell: bash
    env:
      payload: ${{ inputs.payload }}
      method: ${{ inputs.method }}
    run: |
      echo "Sending slack API call"
      echo "method: $method"
      echo "token: ***"
      echo "---- payload ----"
      echo "${payload}"

  - name: Send Message
    if: ${{ steps.context.outputs.send_message == 'true' }}
    uses: slackapi/slack-github-action@v2.0.0
    with:
      errors: true
      token: ${{ inputs.slack_token }}
      method: ${{ inputs.method }}
      payload: ${{ inputs.payload }}
