name: 'Send Slack Message'
description: 'Sends a message to a specified Slack channel'

inputs:
  slack_token:
    description: 'Slack Bot User OAuth Token'
    required: true
  payload:
    description: 'JSON payload to send to Slack'
    required: true
  method:
    description: 'Slack method to call'
    required: true
    default: 'chat.postMessage'

runs:
  using: 'composite'

  steps:
  - name: Raw Slack payload
    uses: slackapi/slack-github-action@v2.0.0
    with:
      errors: true
      method: ${{ inputs.method }}
      token: ${{ inputs.slack_token }}
      payload: ${{ inputs.payload }}
