name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["type:bug", "needs:info"]
projects: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Include in detailed steps how to reproduce the bug you encountered
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: what-expected
    attributes:
      label: What did you expect to happen?
      description: Include details
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true