name: Feature request
description: Filing a Feature request
title: "[Feature]: "
type: feature
labels: ["type:feature", "needs:info"]
projects: []
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        A few sentences describing what the feature aims to achieve. It can be a simple sentence or a story formatted paragraph.
        Be concise and detailed. Avoid vague terms and include relevant links.
      placeholder: |
        As a <blank>, I want to <blank, so that I can <blank>
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: List of milestones or checkpoints that if met verify the task has been completed.
      value: |
          ### Milestones/checkpoints
          - [ ] task 1
    validations:
      required: true
  - type: checkboxes
    id: checks
    attributes:
      label: Checks
      description: Checks before submitting the issue
      options:
        - label: If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"
          required: true

