name: Task/Feature request
description: Filing a Task/Feature request
title: "[Task]: "
labels: ["type:feature", "needs:info", "repository:addons-server", "repository:addons-frontend"]
projects: []
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        A few sentences describing what the task aims to achieve. It can be a simple sentence or a story formatted paragraph.
        Be concise and detailed. Avoid vague terms and include relevant links.
      placeholder: |
        As a <blank>, I want to <blank, so that I can <blank>
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: List of milestones or checkpoints that if met verify the task has been completed.
      value: |
        ```[tasklist]
          ### Milestones/checkpoints
          - [ ] A sentence describing the first milestone/checkpoint
        ```
    validations:
      required: true
  - type: checkboxes
    id: checks
    attributes:
      label: Checks
      description: Checks before submitting the issue
      options:
        - label: If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"
          required: true
  
