name: Login to Google Aritfact Registry
description: Login to GAR and return image configuration for building

inputs:
  service_account:
    required: true
    description: The service account used for GCP
  workload_identity_provider:
    required: true
    description: The workloadd
  registry:
    required: true
    description: The GAR registry

runs:
  using: 'composite'
  steps:
    - name: get the GCP auth token
      id: gcp-auth
      uses: google-github-actions/auth@140bb5113ffb6b65a7e9b937a81fa96cf5064462
      with:
        token_format: access_token
        service_account: ${{ inputs.service_account }}
        workload_identity_provider: ${{ inputs.workload_identity_provider }}

    - name: login to GAR
      if: steps.gcp-auth.outcome == 'success'
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
      with:
        registry: ${{ inputs.registry }}
        username: oauth2accesstoken
        password: ${{ steps.gcp-auth.outputs.access_token }}


