name: Login to Google Aritfact Registry
description: Login to GAR and return image configuration for building

inputs:
  service_account:
    required: true
    description: The service account used for GCP
  workload_identity_provider:
    required: true
    description: The workloadd

outputs:
  registry:
    description: The gar registry
    value: ${{ steps.context.outputs.registry }}
  image:
    description: The gar image to push to
    value: ${{ steps.context.outputs.image }}

runs:
  using: 'composite'
  steps:
    - name: Set Context
      id: context
      shell: bash
      run: |
        echo "registry=us-docker.pkg.dev" >> $GITHUB_OUTPUT
        echo "image=moz-fx-amo-prod/amo-prod/addons-server" >> $GITHUB_OUTPUT

    - name: get the GCP auth token
      id: gcp-auth
      uses: google-github-actions/auth@v2
      with:
        token_format: access_token
        service_account: ${{ inputs.service_account }}
        workload_identity_provider: ${{ inputs.workload_identity_provider }}

    - name: login to GAR
      if: steps.gcp-auth.outcome == 'success'
      uses: docker/login-action@v3
      with:
        registry: ${{ steps.context.outputs.registry }}
        username: oauth2accesstoken
        password: ${{ steps.gcp-auth.outputs.access_token }}


