name: Login to dockerhub
description: Login to dockerhub and return image configuration for building

inputs:
  username:
    required: true
    description: The docker username
  password:
    required: true
    description: The docker password

outputs:
  registry:
    description: The dockerhub registry
    value: ${{ steps.context.outputs.registry }}
  image:
    description: The dockerhub image to push to
    value: ${{ steps.context.outputs.image }}

runs:
  using: 'composite'
  steps:
    - name: Set Context
      id: context
      shell: bash
      run: |
        echo "registry=docker.io" >> $GITHUB_OUTPUT
        echo "image=${{ github.repository }}" >> $GITHUB_OUTPUT

    - name: Login to Dockerhub
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
      with:
        registry: ${{ steps.context.outputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}


