name: Test Actions on Push

on:
  push:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message to send to Slack'
        required: true
        default: 'Hello, world!'
      channel_id:
        description: 'Slack Channel ID to send message to'
        required: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Send Slack Message
        uses: ./.github/actions/slack
        with:
          slack_token: ${{ secrets.SLACK_BOT_TOKEN }}
          message: ${{ inputs.message || 'Hello, world!' }}
          channel_id: ${{ inputs.channel_id || secrets.SLACK_DEFAULT_CHANNEL_ID }}
